#!/usr/bin/env bash
python run_common_voice.py \
    --model_name_or_path="facebook/wav2vec2-large-xlsr-53" \
    --dataset_config_name="mn" \
    --output_dir=/workspace/output_models/mn/wav2vec2-large-xlsr-mongolian-no-1 \
    --cache_dir=/workspace/output_models/mn/.cache \
    --overwrite_output_dir \
    --num_train_epochs="30" \
    --per_device_train_batch_size="32" \
    --per_device_train_batch_size="32" \
    --evaluation_strategy="steps" \
    --learning_rate="3e-4" \
    --warmup_steps="500" \
    --fp16 \
    --save_steps="1000" \
    --eval_steps="1000" \
    --save_total_limit="10" \
    --logging_steps="1000" \
    --group_by_length \
    --feat_proj_dropout="0.0" \
    --layerdrop="0.1" \
    --gradient_checkpointing \
    --do_train \
    --do_eval \
    --dataloader_num_workers=10 \
    --preprocessing_num_workers=10 \
    --load_best_model_at_end \
    --metric_for_best_model="eval_wer" \
    --report_to = 'wandb' \
    --run_name = 'ovhai exp1'
